### PR TITLE
Reduce file size of docker image

### PR DESCRIPTION
**Pull request by floriangeigl**
remove ImageMagick source files and clean apt cache

### CODE REVIEW

**Comment by floriangeigl** [comment]
I would further suggest to add the whole opencv3 installation to the last layer in this file so we can cleanup all temporary files without having them in a layer. (Each layer is just a patch on the previous one. Consequently, cleaning up afterwards does not reduce the size of the final image)

**Comment by floriangeigl** [comment]
In my tests removing ImageMagick source files and cleaning up apt's cache already reduced the size of the image about 1GB.

**Comment by nerdcha** [comment]
This is a great point. The split between layers is a bit awkward here, but IIRC it was because we hit the Docker Hub time limit. But we have a bit of spare time in the `0` and `1` layers now, because the prebuilt TensorFlow `.whl` now works with Python 3.5, so we no longer need to pull and compile TF and all its dependencies. So if this merge doesn't come in under 2 hours, I'll try reshuffling things into the earlier layers.

**Comment by floriangeigl** [comment]
Sounds great! I'm already exited to see how much we were able to reduce the final image size.

**Pull request merged**
